import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "@/component/navigation";
import { MobileNavigation } from "@/component/navigation/mobile-navigation";
import { MovieProvider } from "@/hooks/use-context";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <MovieProvider>
          <div className="min-h-screen bg-background">
            <Navigation />
            <main className="pb-16 md:pb-0">{children}</main>
            <MobileNavigation />
          </div>
        </MovieProvider>
      </body>
    </html>
  );
}
